In [22]:
#enter 4 numbers and store them in a file called number
my_file=open("number.txt","w")
my_list=[3,21,45,83]
for i in my_list:
    my_file.write(str(i))
    my_file.write("\n")
my_file.close()

 

In [8]:
#ask user for their percentage mark and convert it to a grade
user_input = int(input("What is your percentage mark?"))
print(user_input)
if user_input >=70 and user_input <=100:
    print("Your Grade is A - excellent to oustanding")
elif user_input >=60 and user_input <=69:
    print("Your Grade is B -god to very good ")
elif user_input >=50 and user_input <=59:
    print("Your Grade is C -Satisfying pass")
elif user_input >=40 and user_input <=49:
    print("Your Grade is D - Sufficient ")
elif user_input >=30 and user_input <=39:
    print("Your Grade is E -Unsatisfactory ")
elif user_input >=0 and user_input <=29:
    print("Your Grade is F -Unsatisfactory ")
else:
   print("Entry is invalid!")

50
Your Grade is C -Satisfying pass


In [16]:
#The conversion will be done as a function called mark_grade
def mark_grade(user_input):
    if user_input >=70 and user_input <=100:
        print("Your Grade is A - excellent to oustanding")
    elif user_input >=60 and user_input <=69:
        print("Your Grade is B -god to very good ")
    elif user_input >=50 and user_input <=59:
        print("Your Grade is C -Satisfying pass")
    elif user_input >=40 and user_input <=49:
        print("Your Grade is D - Sufficient ")
    elif user_input >=30 and user_input <=39:
        print("Your Grade is E -Unsatisfactory ")
    elif user_input >=0 and user_input <=29:
        print("Your Grade is F -Unsatisfactory ")
    else:
        print("Entry is invalid!")

#ask user for their percentage mark and convert it to a grade
user_input = int(input("What is your percentage mark?"))
print(user_input)

mark_grade(user_input)


58
Your Grade is C -Satisfying pass


In [23]:
#Ask the user for their target grade and print this with their mark
def compare_target(user_input, target_grade):
    if user_input >=70 and user_input <=100:
        print("Your Grade is A - excellent to oustanding ")
    elif user_input >=60 and user_input <=69:
        print("Your Grade is B -god to very good ")
    elif user_input >=50 and user_input <=59:
        print("Your Grade is C -Satisfying pass")
    elif user_input >=40 and user_input <=49:
        print("Your Grade is D - Sufficient ")
    elif user_input >=30 and user_input <=39:
        print("Your Grade is E -Unsatisfactory ")
    elif user_input >=0 and user_input <=29:
        print("Your Grade is F -Unsatisfactory ")
    else:
        print("Entry is invalid!")

#ask user for their percentage mark and convert it to a grade
user_input = int(input("What is your percentage mark?"))
print(user_input)

#ask user for their target grade
target_grade =int(input("What is your target grade?"))
print(target_grade)
if user_input > target_grade:
    print("You have exceeded your target")
elif user_input < target_grade:
    print("You did not achieve your target")
elif user_input == target_grade:
    print("You have achieved your target")
else:
    print("Entry is invalid!")
   

90
70
You have exceeded your target


In [4]:

!pip install numpy


You should consider upgrading via the 'c:\users\adminuser\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [10]:
import numpy as np

In [11]:
#Create a 1D list from 0 to 9
my_1d_list=[1,2,3,4,5,6,7,8,9]
print(my_1d_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
#create an array -  slices data from index 1 to 9 0 indexed
array=np.array([1,2,3,4,5,6,7,8,9])
print(array[1:9])

[2 3 4 5 6 7 8 9]


In [21]:
#Create a 3×3 NumPy array of all Boolean value Trues
import numpy as np
boolean_options=[True, False]
my_2d_list =[[True,True,True],
            [True,True,True],
            [True,True,True]]
boolean_array=np.array (my_2d_list)
            
print(boolean_array)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [28]:
#Extract all odd numbers from array of 1-10
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(" Odd numbers",array[array%2 ==1])

 Odd numbers [1 3 5 7 9]


In [8]:
#Replace all odd numbers in an array of 1-10 with the value -1
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
odd_numb =array[array%2 ==1]
print(odd_numb)
replace_odd_number=(odd_number)=-1
print(replace_odd_number)




[1 3 5 7 9]
-1


In [15]:
#Convert a 1D array to a 2D array with 2rows
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
new_array=array.reshape(2,5)
print(new_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
#Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals
import numpy as np
#create two arrays
a = np.array ([[2,3,8], [4,8,12], [4,5,6]])
b = np.array([[2,3,7], [4,8,2], [6,4,2]])

#stack vertically

output = np.vstack((a, b))
print(output)

#use np.dot to calculate total
c=np.dot(a,b)

print(c)

#np.sum to calculate total
sum=np.sum(c)
print (sum)



[[ 2  3  8]
 [ 4  8 12]
 [ 4  5  6]
 [ 2  3  7]
 [ 4  8  2]
 [ 6  4  2]]
[[ 64  62  36]
 [112 124  68]
 [ 64  76  50]]
656
